import type { Player } from './data';

export const mockPlayers: Player[] = [
  {
    id: '1',
    name: '李明轩',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=1',
    age: 14,
    height: 165,
    weight: 52,
    position: '前锋',
    preferredFoot: '右脚',
    city: '郑州市',
    province: '河南',
    tags: ['速度快', '突破强', '射门准'],
    rating: 78,
    potential: 'A',
    description: '速度快、突破能力强的前锋，射门技术出色',
    phone: '13800138001',
  },
  {
    id: '2',
    name: '王子涵',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=2',
    age: 16,
    height: 178,
    weight: 65,
    position: '中场',
    preferredFoot: '双脚',
    city: '济南市',
    province: '山东',
    tags: ['视野好', '传球准', '控球稳'],
    rating: 82,
    potential: 'A',
    description: '视野开阔、传球精准的中场组织者',
    phone: '13800138002',
  },
  {
    id: '3',
    name: '张宇航',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=3',
    age: 13,
    height: 158,
    weight: 45,
    position: '后卫',
    preferredFoot: '左脚',
    city: '武汉市',
    province: '湖北',
    tags: ['防守稳', '卡位准', '头球好'],
    rating: 72,
    potential: 'B',
    description: '防守稳健、卡位准确的后卫',
    phone: '13800138003',
  },
  {
    id: '4',
    name: '陈浩然',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=4',
    age: 15,
    height: 170,
    weight: 58,
    position: '前锋',
    preferredFoot: '右脚',
    city: '成都市',
    province: '四川',
    tags: ['爆发力强', '射门力量大', '跑位灵活'],
    rating: 76,
    potential: 'A',
    description: '爆发力强、射门力量大的前锋',
    phone: '13800138004',
  },
  {
    id: '5',
    name: '刘子轩',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=5',
    age: 17,
    height: 182,
    weight: 70,
    position: '中场',
    preferredFoot: '双脚',
    city: '广州市',
    province: '广东',
    tags: ['大局观好', '长传准', '防守积极'],
    rating: 80,
    potential: 'B',
    description: '大局观好、长传准确的中场',
    phone: '13800138005',
  },
  {
    id: '6',
    name: '赵俊杰',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=6',
    age: 12,
    height: 150,
    weight: 40,
    position: '后卫',
    preferredFoot: '右脚',
    city: '南京市',
    province: '江苏',
    tags: ['回追快', '铲球准', '对抗强'],
    rating: 68,
    potential: 'A',
    description: '回追速度快、铲球准确的后卫',
    phone: '13800138006',
  },
  {
    id: '7',
    name: '周博文',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=7',
    age: 18,
    height: 188,
    weight: 75,
    position: '门将',
    preferredFoot: '双脚',
    city: '北京市',
    province: '北京',
    tags: ['反应快', '出击果断', '指挥能力强'],
    rating: 85,
    potential: 'B',
    description: '反应速度快、出击果断的门将',
    phone: '13800138007',
  },
  {
    id: '8',
    name: '吴嘉豪',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=8',
    age: 14,
    height: 162,
    weight: 50,
    position: '前锋',
    preferredFoot: '左脚',
    city: '杭州市',
    province: '浙江',
    tags: ['盘带好', '过人强', '射门准'],
    rating: 74,
    potential: 'A',
    description: '盘带出色、过人能力强的前锋',
    phone: '13800138008',
  },
  {
    id: '9',
    name: '孙浩然',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=9',
    age: 16,
    height: 175,
    weight: 62,
    position: '中场',
    preferredFoot: '右脚',
    city: '西安市',
    province: '陕西',
    tags: ['传球准', '视野好', '跑动积极'],
    rating: 79,
    potential: 'B',
    description: '传球准确、视野开阔的中场',
    phone: '13800138009',
  },
  {
    id: '10',
    name: '杨泽宇',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=10',
    age: 17,
    height: 180,
    weight: 68,
    position: '后卫',
    preferredFoot: '双脚',
    city: '长沙市',
    province: '湖南',
    tags: ['防守稳', '卡位准', '长传准'],
    rating: 81,
    potential: 'A',
    description: '防守稳健、卡位准确的后卫',
    phone: '13800138010',
  },
];
